version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=dynamodb,sqs
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"       # Edge port for all LocalStack services
      - "8000:8000"       # DynamoDB service-specific port (optional for DynamoDB local access)
    volumes:
      - "./.localstack:/var/lib/localstack"  # Persist LocalStack data to a local folder
      - "/var/run/docker.sock:/var/run/docker.sock"  # Required for some LocalStack services
